import assert from 'node:assert/strict';
import http from 'node:http';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { runP1S3VisualAccessibilityMatrix } from './p1s3-visual-a11y.mjs';

const MIME=new Map([['.html','text/html; charset=utf-8'],['.mjs','text/javascript; charset=utf-8'],['.js','text/javascript; charset=utf-8'],['.cjs','text/javascript; charset=utf-8'],['.css','text/css; charset=utf-8'],['.json','application/json; charset=utf-8']]);
const pause=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
function safePath(root,pathname){const relative=decodeURIComponent(pathname).replace(/^\/+/, '');const target=path.resolve(root,relative);return target===root||target.startsWith(`${root}${path.sep}`)?target:null}
async function startServer(root){const server=http.createServer(async(req,res)=>{const url=new URL(req.url||'/','http://127.0.0.1'),target=safePath(root,url.pathname);if(!target)return res.writeHead(403).end('Forbidden');try{const body=await readFile(target);res.writeHead(200,{'Content-Type':MIME.get(path.extname(target).toLowerCase())||'application/octet-stream','Cache-Control':'no-store'});res.end(body)}catch{res.writeHead(404).end('Not found')}});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve)});return{server,origin:`http://127.0.0.1:${server.address().port}`}}
async function closeServer(server){if(!server)return;server.closeIdleConnections?.();server.closeAllConnections?.();await new Promise(resolve=>server.close(resolve))}
function diagnose(win,label){win.webContents.on('did-fail-load',(_e,code,description,url)=>console.error(`P1S3 ${label} load ${code} ${url} ${description}`));win.webContents.on('console-message',(_e,level,message,line,source)=>{if(level>=2)console.error(`P1S3 ${label} console[${level}] ${message} @ ${source}:${line}`)});return win}
async function waitFor(win,expression,label,timeout=8000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(win.isDestroyed())throw new Error(`P1S3 window destroyed: ${label}`);try{if(await win.webContents.executeJavaScript(`Boolean(${expression})`,true))return}catch{}await pause(50)}throw new Error(`P1S3 timeout: ${label}`)}
async function assertRuntime(win,prefix){const value=await win.webContents.executeJavaScript(`document.getElementById('runtimeCard')?.textContent||''`,true);assert.ok(value.startsWith(prefix),`P1S3 runtime expected ${prefix}, got ${value}`)}

async function smokeP1S3(win,runtime){
 const ready=`document.querySelector('#moduleRoot')?.dataset.moduleId==='p1s3' && document.querySelectorAll('.module-section').length===6 && document.getElementById('p1s3-position-lab')?.dataset.domainEngine==='position-engine' && document.getElementById('p1s3-block-lab')?.dataset.domainEngine==='transformer-block-engine' && document.getElementById('p1s3-kv-cache-lab')?.dataset.domainEngine==='kv-cache-engine'`;
 await waitFor(win,ready,`${runtime} declarative render`);await assertRuntime(win,runtime);
 const identity=await win.webContents.executeJavaScript(`({title:document.querySelector('.module-hero h1')?.textContent||'',module:document.getElementById('moduleIdentity')?.textContent||'',unsupported:[...document.querySelectorAll('.activity-intro')].filter(n=>/adaptateur de rendu V3 n’est pas encore installé/.test(n.textContent||'')).length})`,true);
 assert.match(identity.title,/Transformer Block Lab/);assert.match(identity.module,/P1S3/);assert.equal(identity.unsupported,0,`${runtime} unsupported activity visible`);

 await win.webContents.executeJavaScript(`localStorage.clear();true`,true);win.webContents.reload();await waitFor(win,ready,`${runtime} clean reload`);

 const rolePrediction=await win.webContents.executeJavaScript(`(() => {const a=document.getElementById('p1s3-role-prediction');if(!a)return null;const values=['Attention','MLP','Résiduel'];const selects=[...a.querySelectorAll('select')];selects.forEach((s,i)=>{s.value=values[i];s.dispatchEvent(new Event('change',{bubbles:true}))});[...a.querySelectorAll('button')].find(b=>/Vérifier mes prédictions/.test(b.textContent||''))?.click();return [...a.querySelectorAll('.prediction-row')].map(n=>n.dataset.state)})()`,true);
 assert.deepEqual(rolePrediction,['correct','correct','correct']);

 const position=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s3-position-lab'),mode=lab?.querySelector('[data-position-mode]'),pos=lab?.querySelector('[data-position-index]');if(!mode||!pos)return null;mode.value='rope';mode.dispatchEvent(new Event('change',{bubbles:true}));pos.value='4';pos.dispatchEvent(new Event('input',{bubbles:true}));return {id:lab.querySelector('[data-position-token-id]')?.textContent||'',base:lab.querySelector('[data-position-base]')?.textContent||'',result:lab.querySelector('[data-position-result]')?.textContent||''}})()`,true);
 assert.equal(position?.id,'4317');assert.notEqual(position?.base,position?.result);assert.match(position?.result||'',/\[/);

 const block=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s3-block-lab');const residual=lab?.querySelector('[data-block-toggle="residual"]');const mlp=lab?.querySelector('[data-block-toggle="mlp"]');if(!residual||!mlp)return null;const before=lab.querySelector('[data-block-stage="output"] code')?.textContent||'';mlp.checked=false;mlp.dispatchEvent(new Event('change',{bubbles:true}));const noMlp=lab.querySelector('[data-block-stage="output"] code')?.textContent||'';residual.checked=false;residual.dispatchEvent(new Event('change',{bubbles:true}));const noResidual=lab.querySelector('[data-block-stage="output"] code')?.textContent||'';return {before,noMlp,noResidual,stages:lab.querySelectorAll('[data-block-stage]').length}})()`,true);
 assert.equal(block?.stages,7);assert.notEqual(block?.before,block?.noMlp);assert.notEqual(block?.noMlp,block?.noResidual);

 const kv=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s3-kv-cache-lab'),past=lab?.querySelector('[data-kv-past]');if(!past)return null;past.value='12';past.dispatchEvent(new Event('input',{bubbles:true}));const metric=(name)=>lab.querySelector('[data-kv-metric="'+name+'"]')?.textContent||'';return {without:metric('without'),with:metric('with'),saved:metric('saved'),stored:metric('stored'),feedback:lab.querySelector('.feedback')?.textContent||''}})()`,true);
 assert.deepEqual({without:kv?.without,with:kv?.with,saved:kv?.saved,stored:kv?.stored},{without:'13',with:'1',saved:'12',stored:'24'});assert.match(kv?.feedback||'',/pas une mémoire utilisateur/);

 const capture=await win.webContents.executeJavaScript(`(() => {for(const id of ['p1s3-position-lab','p1s3-block-lab','p1s3-kv-cache-lab']){const a=document.getElementById(id);const b=[...a.querySelectorAll('button')].find(x=>/Capturer/.test(x.textContent||''));if(!b)return false;b.click()}return true})()`,true);assert.equal(capture,true);
 await waitFor(win,`Number((document.getElementById('eventCount')?.textContent||'0').match(/\\d+/)?.[0]||0)>=6`,`${runtime} P1S3 events`);

 const submitted=await win.webContents.executeJavaScript(`(() => {function complete(id,re){const a=document.getElementById(id);if(!a)return false;for(const q of a.querySelectorAll('fieldset.question')){const input=q.querySelector('input[type="radio"]');if(!input)return false;input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}))}const b=[...a.querySelectorAll('button')].find(x=>re.test(x.textContent||''));if(!b)return false;b.click();return true}return complete('p1s3-quiz',/Corriger le quiz/)&&complete('p1s3-transfer',/Vérifier le transfert/)})()`,true);
 assert.equal(submitted,true,`${runtime} P1S3 assessment could not be submitted`);
 await waitFor(win,`(() => {const raw=localStorage.getItem('latent-v3-progress')||'';return raw.includes('"p1s3"')&&raw.includes('"quiz"')&&raw.includes('"transfer"')})()`,`${runtime} P1S3 persistence`);
 const before=await win.webContents.executeJavaScript(`document.getElementById('masteryStatus')?.dataset.state||''`,true);assert.ok(['learning','evidence','mastered'].includes(before));win.webContents.reload();await waitFor(win,ready,`${runtime} persisted reload`);const after=await win.webContents.executeJavaScript(`document.getElementById('masteryStatus')?.dataset.state||''`,true);assert.equal(after,before,`${runtime} P1S3 mastery must persist`);
}

async function makeWebWindow(BrowserWindow,url,label){const win=diagnose(new BrowserWindow({width:1360,height:900,show:false,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}}),label);await win.loadURL(url);return win}

export async function runP1S3E2E({app,BrowserWindow,APP_ROOT,WEB_ENTRY,createWindow}){const artifactDir=path.join(APP_ROOT,'artifacts','visual-a11y');await mkdir(artifactDir,{recursive:true});let server;const windows=[];let exitCode=0;try{const host=await startServer(APP_ROOT);server=host.server;console.log('▶ P1S3 E2E Web');const web=await makeWebWindow(BrowserWindow,`${host.origin}/${WEB_ENTRY}?module=p1s3`,'Web');windows.push(web);await smokeP1S3(web,'Web');await runP1S3VisualAccessibilityMatrix(web,{runtime:'Web',artifactDir});console.log('▶ P1S3 E2E Web ✓');console.log('▶ P1S3 E2E Electron');const electron=diagnose(createWindow({entry:`${WEB_ENTRY}?module=p1s3`,showWhenReady:false}),'Electron');windows.push(electron);await smokeP1S3(electron,'Electron');await runP1S3VisualAccessibilityMatrix(electron,{runtime:'Electron',artifactDir});console.log('▶ P1S3 E2E Electron ✓');console.log('✅ P1S3 LATENT V3 — Block/Position/KV + Web/Electron + Visual/A11y validés.')}catch(error){exitCode=1;console.error('❌ P1S3 E2E FAILED');console.error(error?.stack||error)}finally{for(const win of windows)if(!win.isDestroyed())win.destroy();await closeServer(server)}return exitCode}
