import assert from 'node:assert/strict';
import http from 'node:http';
import { mkdir, readFile } from 'node:fs/promises';
import path from 'node:path';
import { runP1S4VisualAccessibilityMatrix } from './p1s4-visual-a11y.mjs';

const MIME=new Map([['.html','text/html; charset=utf-8'],['.mjs','text/javascript; charset=utf-8'],['.js','text/javascript; charset=utf-8'],['.cjs','text/javascript; charset=utf-8'],['.css','text/css; charset=utf-8'],['.json','application/json; charset=utf-8']]);
const pause=(ms)=>new Promise(resolve=>setTimeout(resolve,ms));
function safePath(root,pathname){const relative=decodeURIComponent(pathname).replace(/^\/+/, '');const target=path.resolve(root,relative);return target===root||target.startsWith(`${root}${path.sep}`)?target:null}
async function startServer(root){const server=http.createServer(async(req,res)=>{const url=new URL(req.url||'/','http://127.0.0.1'),target=safePath(root,url.pathname);if(!target)return res.writeHead(403).end('Forbidden');try{const body=await readFile(target);res.writeHead(200,{'Content-Type':MIME.get(path.extname(target).toLowerCase())||'application/octet-stream','Cache-Control':'no-store'});res.end(body)}catch{res.writeHead(404).end('Not found')}});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve)});return{server,origin:`http://127.0.0.1:${server.address().port}`}}
async function closeServer(server){if(!server)return;server.closeIdleConnections?.();server.closeAllConnections?.();await new Promise(resolve=>server.close(resolve))}
function diagnose(win,label){win.webContents.on('did-fail-load',(_e,code,description,url)=>console.error(`P1S4 ${label} load ${code} ${url} ${description}`));win.webContents.on('console-message',(_e,level,message,line,source)=>{if(level>=2)console.error(`P1S4 ${label} console[${level}] ${message} @ ${source}:${line}`)});return win}
async function waitFor(win,expression,label,timeout=8000){const deadline=Date.now()+timeout;while(Date.now()<deadline){if(win.isDestroyed())throw new Error(`P1S4 window destroyed: ${label}`);try{if(await win.webContents.executeJavaScript(`Boolean(${expression})`,true))return}catch{}await pause(50)}throw new Error(`P1S4 timeout: ${label}`)}
async function assertRuntime(win,prefix){const value=await win.webContents.executeJavaScript(`document.getElementById('runtimeCard')?.textContent||''`,true);assert.ok(value.startsWith(prefix),`P1S4 runtime expected ${prefix}, got ${value}`)}

async function smokeP1S4(win,runtime){
 const ready=`document.querySelector('#moduleRoot')?.dataset.moduleId==='p1s4' && document.querySelectorAll('.module-section').length===6 && document.getElementById('p1s4-sampling-lab')?.dataset.domainEngine==='sampling-engine' && document.getElementById('p1s4-truth-lab')?.dataset.domainEngine==='sampling-engine' && document.getElementById('p1s4-loop-lab')?.dataset.domainEngine==='sampling-engine'`;
 await waitFor(win,ready,`${runtime} declarative render`);await assertRuntime(win,runtime);
 const identity=await win.webContents.executeJavaScript(`({title:document.querySelector('.module-hero h1')?.textContent||'',module:document.getElementById('moduleIdentity')?.textContent||'',unsupported:[...document.querySelectorAll('.activity-intro')].filter(n=>/adaptateur de rendu V3 n’est pas encore installé/.test(n.textContent||'')).length})`,true);
 assert.match(identity.title,/Sampling et décodage/);assert.match(identity.module,/P1S4/);assert.equal(identity.unsupported,0,`${runtime} unsupported activity visible`);

 await win.webContents.executeJavaScript(`localStorage.clear();true`,true);win.webContents.reload();await waitFor(win,ready,`${runtime} clean reload`);

 const prediction=await win.webContents.executeJavaScript(`(() => {const a=document.getElementById('p1s4-three-candidate-prediction');if(!a)return null;const values=['calcule','Oui'];const selects=[...a.querySelectorAll('select')];selects.forEach((s,i)=>{s.value=values[i];s.dispatchEvent(new Event('change',{bubbles:true}))});[...a.querySelectorAll('button')].find(b=>/Vérifier mes prédictions/.test(b.textContent||''))?.click();return {states:[...a.querySelectorAll('.prediction-row')].map(n=>n.dataset.state),feedback:a.querySelector('.feedback')?.textContent||''}})()`,true);
 assert.deepEqual(prediction?.states,['correct','correct']);assert.match(prediction?.feedback||'',/2\/2/);

 const baseline=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s4-sampling-lab');const rows=[...lab.querySelectorAll('[data-sampling-rows] tr')];return {selected:lab.querySelector('[data-sampling-selected]')?.textContent||'',rows:rows.length,base:rows.map(r=>r.children[2]?.querySelector('small')?.textContent||''),eligible:rows.map(r=>r.dataset.eligible)}})()`,true);
 assert.equal(baseline?.rows,3);assert.equal(baseline?.selected,'calcule');assert.deepEqual(baseline?.eligible,['true','true','true']);assert.match(baseline?.base?.[0]||'',/66[,.]5/);

 const filtered=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s4-sampling-lab'),f=lab.querySelector('[data-sampling-filter]'),p=lab.querySelector('[data-sampling-topp]'),t=lab.querySelector('[data-sampling-temperature]');f.value='topp';f.dispatchEvent(new Event('change',{bubbles:true}));p.value='0.8';p.dispatchEvent(new Event('input',{bubbles:true}));t.value='1';t.dispatchEvent(new Event('input',{bubbles:true}));return [...lab.querySelectorAll('[data-sampling-rows] tr')].map(r=>({eligible:r.dataset.eligible,final:r.children[4]?.textContent||''}))})()`,true);
 assert.deepEqual(filtered?.map(x=>x.eligible),['true','true','false']);assert.match(filtered?.[2]?.final||'',/^0[,.]0 %$/);

 const temperature=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s4-sampling-lab'),f=lab.querySelector('[data-sampling-filter]'),t=lab.querySelector('[data-sampling-temperature]');f.value='none';f.dispatchEvent(new Event('change',{bubbles:true}));const pct=()=>Number((lab.querySelector('[data-sampling-rows] tr small')?.textContent||'0').replace(',','.').replace('%','').trim());t.value='1';t.dispatchEvent(new Event('input',{bubbles:true}));const base=pct();t.value='0.5';t.dispatchEvent(new Event('input',{bubbles:true}));return {base,low:pct(),selected:lab.querySelector('[data-sampling-selected]')?.textContent||''}})()`,true);
 assert.ok(temperature?.low>temperature?.base,`${runtime} low temperature must sharpen top candidate`);assert.equal(temperature?.selected,'calcule');

 const nonMax=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s4-sampling-lab'),strategy=lab.querySelector('[data-sampling-strategy]'),seed=lab.querySelector('[data-sampling-seed]'),filter=lab.querySelector('[data-sampling-filter]'),temp=lab.querySelector('[data-sampling-temperature]');strategy.value='sample';strategy.dispatchEvent(new Event('change',{bubbles:true}));filter.value='none';filter.dispatchEvent(new Event('change',{bubbles:true}));temp.value='1';temp.dispatchEvent(new Event('input',{bubbles:true}));for(let s=0;s<100;s++){seed.value=String(s);seed.dispatchEvent(new Event('change',{bubbles:true}));const chosen=lab.querySelector('[data-sampling-selected]')?.textContent||'';if(chosen&&chosen!=='calcule')return {seed:s,chosen}}return null})()`,true);
 assert.ok(nonMax&&['choisit','hésite'].includes(nonMax.chosen),`${runtime} weighted sampling never produced a non-max candidate`);

 const truth=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s4-truth-lab'),t=lab.querySelector('[data-truth-temperature]');const pct=()=>Number((lab.querySelector('.truth-row strong')?.textContent||'0').replace(',','.').replace('%','').trim());t.value='1';t.dispatchEvent(new Event('input',{bubbles:true}));const base=pct();t.value='0.3';t.dispatchEvent(new Event('input',{bubbles:true}));return {base,low:pct(),feedback:lab.querySelector('.feedback')?.textContent||''}})()`,true);
 assert.ok(truth?.low>truth?.base,`${runtime} Truth Trap low T must reinforce dominant false candidate`);assert.match(truth?.feedback||'',/aucune source externe/i);assert.match(truth?.feedback||'',/aucune vérité/i);

 const loop=await win.webContents.executeJavaScript(`(() => {const lab=document.getElementById('p1s4-loop-lab'),reset=lab.querySelector('[data-loop-reset]'),generate=lab.querySelector('[data-loop-generate]');reset.click();const before=[...lab.querySelectorAll('.loop-candidate .sampling-token')].map(n=>n.textContent);generate.click();const after=[...lab.querySelectorAll('.loop-candidate .sampling-token')].map(n=>n.textContent);return {before,after,context:lab.querySelector('[data-loop-context]')?.textContent||'',state:lab.querySelector('[data-loop-state]')?.textContent||'',history:lab.querySelectorAll('[data-loop-history] li').length}})()`,true);
 assert.equal(loop?.history,1);assert.ok((loop?.context||'').length>'Le modèle'.length);assert.notDeepEqual(loop?.after,loop?.before);assert.notEqual(loop?.state,'start');

 const captured=await win.webContents.executeJavaScript(`(() => {const sampling=document.querySelector('#p1s4-sampling-lab [data-sampling-decide]'),truth=document.querySelector('#p1s4-truth-lab [data-truth-capture]');if(!sampling||!truth)return false;sampling.click();truth.click();return true})()`,true);assert.equal(captured,true);
 await waitFor(win,`Number((document.getElementById('eventCount')?.textContent||'0').match(/\\d+/)?.[0]||0)>=8`,`${runtime} P1S4 events`);

 const submitted=await win.webContents.executeJavaScript(`(() => {function complete(id,re){const a=document.getElementById(id);if(!a)return false;for(const q of a.querySelectorAll('fieldset.question')){const input=q.querySelector('input[type="radio"]');if(!input)return false;input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}))}const b=[...a.querySelectorAll('button')].find(x=>re.test(x.textContent||''));if(!b)return false;b.click();return true}return complete('p1s4-quiz',/Corriger le quiz/)&&complete('p1s4-transfer',/Vérifier le transfert/)})()`,true);
 assert.equal(submitted,true,`${runtime} P1S4 assessment could not be submitted`);
 await waitFor(win,`(() => {const raw=localStorage.getItem('latent-v3-progress')||'';return raw.includes('"p1s4"')&&raw.includes('"quiz"')&&raw.includes('"transfer"')})()`,`${runtime} P1S4 persistence`);
 const before=await win.webContents.executeJavaScript(`document.getElementById('masteryStatus')?.dataset.state||''`,true);assert.ok(['learning','evidence','mastered'].includes(before));win.webContents.reload();await waitFor(win,ready,`${runtime} persisted reload`);const after=await win.webContents.executeJavaScript(`document.getElementById('masteryStatus')?.dataset.state||''`,true);assert.equal(after,before,`${runtime} P1S4 mastery must persist`);
}

async function makeWebWindow(BrowserWindow,url,label){const win=diagnose(new BrowserWindow({width:1360,height:900,show:false,webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true,webSecurity:true}}),label);await win.loadURL(url);return win}

export async function runP1S4E2E({app,BrowserWindow,APP_ROOT,WEB_ENTRY,createWindow}){const artifactDir=path.join(APP_ROOT,'artifacts','visual-a11y');await mkdir(artifactDir,{recursive:true});let server;const windows=[];let exitCode=0;try{const host=await startServer(APP_ROOT);server=host.server;console.log('▶ P1S4 E2E Web');const web=await makeWebWindow(BrowserWindow,`${host.origin}/${WEB_ENTRY}?module=p1s4`,'Web');windows.push(web);await smokeP1S4(web,'Web');await runP1S4VisualAccessibilityMatrix(web,{runtime:'Web',artifactDir});console.log('▶ P1S4 E2E Web ✓');console.log('▶ P1S4 E2E Electron');const electron=diagnose(createWindow({entry:`${WEB_ENTRY}?module=p1s4`,showWhenReady:false}),'Electron');windows.push(electron);await smokeP1S4(electron,'Electron');await runP1S4VisualAccessibilityMatrix(electron,{runtime:'Electron',artifactDir});console.log('▶ P1S4 E2E Electron ✓');console.log('✅ P1S4 LATENT V3 — Sampling/Truth/Autoregression + Web/Electron + Visual/A11y validés.')}catch(error){exitCode=1;console.error('❌ P1S4 E2E FAILED');console.error(error?.stack||error)}finally{for(const win of windows)if(!win.isDestroyed())win.destroy();await closeServer(server)}return exitCode}
